[[LSODA]]
arch = "aarch64"
git-tree-sha1 = "69ba46a3809fe8dfe43c5f58984f32173549132d"
os = "macos"

    [[LSODA.download]]
    sha256 = "782c730c62b863d41db12fde476ae90218d61efe21e31c51474ef0cae5b7e97a"
    url = "https://github.com/JuliaBinaryWrappers/LSODA_jll.jl/releases/download/LSODA-v0.1.2+0/LSODA.v0.1.2.aarch64-apple-darwin.tar.gz"
[[LSODA]]
arch = "aarch64"
git-tree-sha1 = "1133221eeb2a7b741489548b1973ee9ccdb23a1d"
libc = "glibc"
os = "linux"

    [[LSODA.download]]
    sha256 = "cd2d7658ada2f73e529fe7b5784ed568b28a2993788e9f66f2018eb195be55ec"
    url = "https://github.com/JuliaBinaryWrappers/LSODA_jll.jl/releases/download/LSODA-v0.1.2+0/LSODA.v0.1.2.aarch64-linux-gnu.tar.gz"
[[LSODA]]
arch = "aarch64"
git-tree-sha1 = "dc5ec60e2da43457ae65cdad28e5e0895b82c817"
libc = "musl"
os = "linux"

    [[LSODA.download]]
    sha256 = "a517ea33ec0f7976b4d185dc469d83e09318b2733fe0547f8d44c32f07e4d4b1"
    url = "https://github.com/JuliaBinaryWrappers/LSODA_jll.jl/releases/download/LSODA-v0.1.2+0/LSODA.v0.1.2.aarch64-linux-musl.tar.gz"
[[LSODA]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "abf7113c5488a80655069e44c09816fcb3fb2d7f"
libc = "glibc"
os = "linux"

    [[LSODA.download]]
    sha256 = "54161fb7a639f9e29401e1ed82f2bcb8fe42163c60e9382560ac7a3dd72b44d9"
    url = "https://github.com/JuliaBinaryWrappers/LSODA_jll.jl/releases/download/LSODA-v0.1.2+0/LSODA.v0.1.2.armv6l-linux-gnueabihf.tar.gz"
[[LSODA]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "77d02dd4455f80cb75fdc5bd7907b4d27012f4cd"
libc = "musl"
os = "linux"

    [[LSODA.download]]
    sha256 = "cb93e0bfa4f91d86159cb3162a4e37c137170bcbd6edca4a5ad0c04d23ab5e47"
    url = "https://github.com/JuliaBinaryWrappers/LSODA_jll.jl/releases/download/LSODA-v0.1.2+0/LSODA.v0.1.2.armv6l-linux-musleabihf.tar.gz"
[[LSODA]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "80d09790333c74b58c102ac44c9250b1784757ad"
libc = "glibc"
os = "linux"

    [[LSODA.download]]
    sha256 = "6f2cb7cc089a6af88a7d069b11fd53e72d64cb5bc8db463d6676f314c9a29d67"
    url = "https://github.com/JuliaBinaryWrappers/LSODA_jll.jl/releases/download/LSODA-v0.1.2+0/LSODA.v0.1.2.armv7l-linux-gnueabihf.tar.gz"
[[LSODA]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5a550c8a3b47fd34296409d7b5148b2fe97eeba1"
libc = "musl"
os = "linux"

    [[LSODA.download]]
    sha256 = "6047048c79592c2ae9004087a90a234f5dba8932c7ff158f3dda4ca5484715ba"
    url = "https://github.com/JuliaBinaryWrappers/LSODA_jll.jl/releases/download/LSODA-v0.1.2+0/LSODA.v0.1.2.armv7l-linux-musleabihf.tar.gz"
[[LSODA]]
arch = "i686"
git-tree-sha1 = "37a4d3fb0b66bb3da95ed9accee2f31bcf4c583b"
libc = "glibc"
os = "linux"

    [[LSODA.download]]
    sha256 = "06a17f2d326dafc8044ba7e85dfa51b0bbfc21be2c8dd3ef7b40fc918b7e56a1"
    url = "https://github.com/JuliaBinaryWrappers/LSODA_jll.jl/releases/download/LSODA-v0.1.2+0/LSODA.v0.1.2.i686-linux-gnu.tar.gz"
[[LSODA]]
arch = "i686"
git-tree-sha1 = "5bea335c7c7ac69cd26f5414b430384b06c647ec"
libc = "musl"
os = "linux"

    [[LSODA.download]]
    sha256 = "b3d852113040e427f07601364b5f85e186f94c0c34ab42ea724a5ac5aa0b1ebb"
    url = "https://github.com/JuliaBinaryWrappers/LSODA_jll.jl/releases/download/LSODA-v0.1.2+0/LSODA.v0.1.2.i686-linux-musl.tar.gz"
[[LSODA]]
arch = "i686"
git-tree-sha1 = "840963f8ef774f02b1252d0d56805004d8cc4ee9"
os = "windows"

    [[LSODA.download]]
    sha256 = "97405d7a2f22536533cf653e95ebc9f64c433114a3f176d8376754cf3367b39a"
    url = "https://github.com/JuliaBinaryWrappers/LSODA_jll.jl/releases/download/LSODA-v0.1.2+0/LSODA.v0.1.2.i686-w64-mingw32.tar.gz"
[[LSODA]]
arch = "powerpc64le"
git-tree-sha1 = "c302e6ea9cf9dd77e00d3aeff5aed3e57f660675"
libc = "glibc"
os = "linux"

    [[LSODA.download]]
    sha256 = "980955129227b9be76e08ad8fd2f36f27b94399d8d42ddc876ae2c2a6f1c8360"
    url = "https://github.com/JuliaBinaryWrappers/LSODA_jll.jl/releases/download/LSODA-v0.1.2+0/LSODA.v0.1.2.powerpc64le-linux-gnu.tar.gz"
[[LSODA]]
arch = "x86_64"
git-tree-sha1 = "cdb031214a8e0b7cd4429351c6044fd99c58b7b4"
os = "macos"

    [[LSODA.download]]
    sha256 = "b1401b51e138dfb489e3959bf8ebfb2911548362e72a91be339be00be7bf311d"
    url = "https://github.com/JuliaBinaryWrappers/LSODA_jll.jl/releases/download/LSODA-v0.1.2+0/LSODA.v0.1.2.x86_64-apple-darwin.tar.gz"
[[LSODA]]
arch = "x86_64"
git-tree-sha1 = "b1c6d5aef366f4de75e0e5a0b63d783f043b2321"
libc = "glibc"
os = "linux"

    [[LSODA.download]]
    sha256 = "7a85af33992bde40ca40aaa6e8ae29bfffc8ada42dac08f3e3ddd8c5458ba8f1"
    url = "https://github.com/JuliaBinaryWrappers/LSODA_jll.jl/releases/download/LSODA-v0.1.2+0/LSODA.v0.1.2.x86_64-linux-gnu.tar.gz"
[[LSODA]]
arch = "x86_64"
git-tree-sha1 = "4dc5a4bf1f64a822530846deec4f770b9d3716ee"
libc = "musl"
os = "linux"

    [[LSODA.download]]
    sha256 = "6b15d595df8633599f16861ce748168f07b7a24565cc32a84fc605cdc12a4468"
    url = "https://github.com/JuliaBinaryWrappers/LSODA_jll.jl/releases/download/LSODA-v0.1.2+0/LSODA.v0.1.2.x86_64-linux-musl.tar.gz"
[[LSODA]]
arch = "x86_64"
git-tree-sha1 = "10a6b6d40968438fcb727148fbb2433e9f6da241"
os = "freebsd"

    [[LSODA.download]]
    sha256 = "9a3bd524b8eaf6904864e28987eed71467ca00cdc75f9a51c390ceeadf2199db"
    url = "https://github.com/JuliaBinaryWrappers/LSODA_jll.jl/releases/download/LSODA-v0.1.2+0/LSODA.v0.1.2.x86_64-unknown-freebsd.tar.gz"
[[LSODA]]
arch = "x86_64"
git-tree-sha1 = "cfc6551fdb12cc130892afc45e10eb02a59fbc12"
os = "windows"

    [[LSODA.download]]
    sha256 = "4d2f56ddf60763e0f1b8fc7e57d6e94a6fc0b064c30013313ea2dd89d88b1901"
    url = "https://github.com/JuliaBinaryWrappers/LSODA_jll.jl/releases/download/LSODA-v0.1.2+0/LSODA.v0.1.2.x86_64-w64-mingw32.tar.gz"
