# Autogenerated wrapper script for LSODA_jll for x86_64-w64-mingw32
export liblsoda

JLLWrappers.@generate_wrapper_header("LSODA")
JLLWrappers.@declare_library_product(liblsoda, "liblsoda.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        liblsoda,
        "bin\\liblsoda.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
